### ISSUE TITLE
[Bug] Curations under 100KB show as 0.0MB

### ISSUE THREAD

**Issue by VFDan** [Dri0m/flashpoint-submission-system#12]
They should show as whatever amount of KB it is (for this one, 3.4KB).
![image](https://user-images.githubusercontent.com/44413950/124986895-2cbfe380-e00a-11eb-9de3-5cddb8cadbab.png)

**Comment by colin969** [comment]
https://yourbasic.org/golang/formatting-byte-size-to-human-readable-format/

**Comment by Dri0m** [comment]
fixed in https://github.com/Dri0m/flashpoint-submission-system/commit/0723e99dde33a203df4862321bdf7b0508aab94b
