### ISSUE TITLE
[Bug] The "Series" meta field shows as blank when viewing a submission 

### ISSUE THREAD

**Issue by Soulsderfuchs** [Dri0m/flashpoint-submission-system#15]
All the other empty fields show that the field is indeed empty.
![chrome_YQC7L1zYet](https://user-images.githubusercontent.com/59575350/124991122-de5d1580-e006-11eb-882a-6923d0aa14e1.png)

Edit 1: It seems the field breaks at random like in https://fpfss.unstable.life/web/submission/33 because in https://fpfss.unstable.life/web/submission/13 it shows fine.

Edit 2 : https://fpfss.unstable.life/web/submission/41 also has it plus the developer field is also blank.

**Comment by colin969** [comment]
The value itself is an empty string, not an undefined one. This shouldn't be possible for people manually exporting anyway.

**Comment by Soulsderfuchs** [comment]
Can confirm that this is due to people messing with the meta.yaml file directly or still using meta.txt.

**Comment by Dri0m** [comment]
not a bug
