### ISSUE TITLE
Viewable Submissions for Trial Curators

### ISSUE THREAD

**Issue by TheTort** [Dri0m/flashpoint-submission-system#16]
Trial Curators would be able to view curations that are not there's
but they cannot comment on them

the benefits would be:

trial curators would see if it was curated already
would be very useful for playing curations early

**Comment by Dri0m** [comment]
partially done in https://github.com/Dri0m/flashpoint-submission-system/commit/af28b2714e879a2ccf4597e60a08d870d476d581

**Comment by Dri0m** [comment]
i consider this done for now, there are some visual issues (visible actions that should be hidden) but that can be fixed later
