### ISSUE TITLE
Error messages do not appear to be formatted/executed properly

### ISSUE THREAD

**Issue by muzikbike** [Dri0m/flashpoint-submission-system#17]
![err1](https://user-images.githubusercontent.com/52297970/125000355-19336d80-e048-11eb-89aa-392919c784ff.png)
![err2](https://user-images.githubusercontent.com/52297970/125000358-19336d80-e048-11eb-938b-7d70e27e0102.png)

**Comment by Dri0m** [comment]
they are formatted just as they should be, the fact that it returns a plain JSON instead of a fancy error page is just because it's easier to do (:
