### ISSUE TITLE
[Bug(?)] Verifying a submission without leaving a comment makes the message empty

### ISSUE THREAD

**Issue by MagnificentNoodle** [Dri0m/flashpoint-submission-system#18]
I feel like it should be saying _Verified the submission._ like the other actions

![image](https://user-images.githubusercontent.com/87150948/125034388-88b45780-e05e-11eb-9393-aa0a4e051276.png)

**Comment by Dri0m** [comment]
fixed in https://github.com/Dri0m/flashpoint-submission-system/commit/2ee664de422838c6178ad294b0a3cdc35962f6d6
