### ISSUE TITLE
[Bug] Tag description tooltips get cut short upon encountering <code> html tag from wiki

### ISSUE THREAD

**Issue by MagnificentNoodle** [Dri0m/flashpoint-submission-system#19]
![image](https://user-images.githubusercontent.com/87150948/125037604-5ad11200-e062-11eb-8319-05a327bc403e.png)
![image](https://user-images.githubusercontent.com/87150948/125037678-6de3e200-e062-11eb-88c3-4c3cd8436aef.png)

![image](https://user-images.githubusercontent.com/87150948/125039205-3c6c1600-e064-11eb-988c-17b877611311.png)
![image](https://user-images.githubusercontent.com/87150948/125039259-4b52c880-e064-11eb-85d6-04d28b5efd86.png)

**Comment by colin969** [comment]
It's using the title value, it needs to be a custom dialog or it hits limits.

**Comment by Dri0m** [comment]
https://github.com/Dri0m/flashpoint-submission-system/issues/39

**Comment by Dri0m** [comment]
it will be tracked in https://github.com/Dri0m/flashpoint-submission-system/issues/39
