### ISSUE TITLE
[Bug] Games with very long single word titles don't wrap in table

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#22]
Games that have a long one word title don't wrap the way long multi-word titles do. This makes the table very wide and all of the important info is pushed way off to the right.

The curation that caused this: https://fpfss.unstable.life/web/submission/239

![Example](https://user-images.githubusercontent.com/87086984/125149987-6546e680-e10a-11eb-9a79-039c4847d023.PNG)

**Comment by muzikbike** [comment]
Can confirm.

**Comment by Dri0m** [comment]
fixed, break is applied for titles (and filenames) with a word longer than 35 characters
