### ISSUE TITLE
[Suggestion] Reset RC, Approval and Verification counts to 0 after new version upload

### ISSUE THREAD

**Issue by MagnificentNoodle** [Dri0m/flashpoint-submission-system#23]
It is kind of misleading to have a submission still have requested changes on it after a new version has been uploaded. Resetting the counts would mean that the approval process starts fresh when a new version is uploaded.

**Comment by Dri0m** [comment]
it does start fresh, but requested changes persist until the testes rechecks it, that's intentional

**Comment by MagnificentNoodle** [comment]
Gotcha, closing in that case
