### ISSUE TITLE
Ability to sort curation list by parameter

### ISSUE THREAD

**Issue by muzikbike** [Dri0m/flashpoint-submission-system#25]
Preferably just by clicking that column top in specific, as to allow for alphabetical sorting of all curations listed, or the curator, or so on...

**Comment by Dri0m** [comment]
![image](https://user-images.githubusercontent.com/8342007/125209749-53487d80-e29b-11eb-84d8-41cb44fed163.png)
there are basic sort filters, i don't really understand when would you need to sort by alphabet or user's name?
