### ISSUE TITLE
[Bug] Meta doesn't display properly when the curation has a meta.txt

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#27]
The meta's for the few people that still write meta.txt instead of using meta.yaml do not display all fields properly on the site. The Source and Launch command fields cut off after http/https, Original Description doesn't show at all, and there may be other issues not so easily noticed.

For an example, see: https://fpfss.unstable.life/web/submission/576 or any of Tallamar's other curations.

I totally get if this is just an unavoidable thing of using meta.txt though.

**Comment by Dri0m** [comment]
Tell Tallamar to stop writing meta by hand years after it was deprecated.
