### ISSUE TITLE
Parallel upload queue limit can be bypassed

### ISSUE THREAD

**Issue by childishbeat** [Dri0m/flashpoint-submission-system#3]
Typing a higher number into the text box bypasses the limit of 20. However, except for numbers with e, which change the value to 1 with the up or down arrow, until a valid value is entered, up does nothing and down decreases the number back to 20. The ideal solution is to automatically change the text box to 20 when a higher number is entered, or 1 for numbers with e.

**Comment by Dri0m** [comment]
At the moment, nothing stops the user from simply opening multiple tabs and running more queues that way. Or hitting the upload endpoint directly. This is not an issue really, I don't see much point blocking this (except for better UI, which is also questionable).

**Comment by childishbeat** [comment]
Cool. Sorry for the late reply, I never thought to come back here until stumbling upon the message.
