### ISSUE TITLE
[Suggestion] Make it more obvious to curators that an Audition has been submitted

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#31]
Right now auditions are getting buried because we curators don't know when one's been submitted. I just requested changes on one that'd been sitting in the queue for four days. Obviously people aren't searching to see if auditions are needing approval. And sometimes people submit auditions without ever saying anything in the server first, so we don't even know to watch for them.

A good solution to this might be to have the Notification Bot post the upload notification for auditions in the curator-auditions channel either as well as or instead of posting in the normal upload feed. That way we'll know that one's been submitted and if auditioners have uploaded fixed versions if asked to.

**Comment by Dri0m** [comment]
> Obviously people aren't searching to see if auditions are needing approval.


Maybe they should... If you're interested in checking auditions, you should spend 5 seconds setting up a filter bookmark to search for unchecked auditions, the search filter URLs are static for this reason. Fixed version upload should notify you if you're subscribing to the auditions.
