### ISSUE TITLE
Upload all prior curations to FPFSS

### ISSUE THREAD

**Issue by muzikbike** [Dri0m/flashpoint-submission-system#36]
All data from the current curation channels would be uploaded to FPFSS, and curations assigned to the discord accounts which posted them accordingly. Ties in with #35 as to allow for meta fixes, alternate adding, and other stuff for existing Flashpoint content instead of having to still use discord for it.

**Comment by Dri0m** [comment]
pre-FPFSS curations will be available within FPFSS only as legacy entries
