### ISSUE TITLE
[Bug] Batch Actions don't work properly with quick filters on

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#4]
Batch Downloading works fine, but all of the other batch actions aren't working properly if you have a quick filter on or if you've searched for something. They will only apply whichever action you chose to the first one you checked, not all of them. Works fine if you're on the main browse submissions page and haven't searched or used a filter.

**Comment by Dri0m** [comment]
should be fixed in https://github.com/Dri0m/flashpoint-submission-system/commit/3b2ee6584d7c356039e3b1c1eeaed938f00abbac
