### ISSUE TITLE
[Bug] [critical] Error 0 when uploading larger files

### ISSUE THREAD

**Issue by Onmp314** [Dri0m/flashpoint-submission-system#40]
This error occurs when the files are larger than 5 or 10 MB. 

Steps to reproduce:
1. enter to: https://fpfss.unstable.life/web
2. check if you are a Trial Curator or just a Curator
3. click Sumbit
4. try to upload a larger file, e.g. a 50 MB file
5. sometimes something like this will appear:
[file].7z
Upload failed!
Request status: 0 - undefined
Server response:

**Comment by Onmp314** [comment]
There is a solution for this: just increase the Parallel update queries, e.g. to 5.

Therefore, I am closing this issue.

**Comment by Onmp314** [comment]
This solution is temporary, so you need to reopen it.

**Comment by Dri0m** [comment]
a new uploader system has been deployed, this should not happen anymore
