### ISSUE TITLE
[Bug] Submission Rejection Doesn’t Stop the Flow 

### ISSUE THREAD

**Issue by Soulsderfuchs** [Dri0m/flashpoint-submission-system#42]
If a submission gets rejected it should block all actions done to it. The way it is now enables the flow to start all over again even having been marked as a rejection , so it could in theory be able to reject more than once , or verify a rejected submission.

**Comment by Dri0m** [comment]
I don't see a reason to block discussion about a rejected submission, people can do whatever they want if it's rejected, it's filtered out of most relevant search filters anyway.
