### ISSUE TITLE
[Suggestion/Bug/idk] Curator approving a submission should remove all RCs not just the ones they requested

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#43]
Currently if a curator requests changes on a submission, only they can approve those changes. The RC stays if a different curator approves it. This causes problems when the original curator doesn't return to approve the changes. The submission will never be considered "Ready for Verification" since it has an active RC, despite being approved.

**Comment by Dri0m** [comment]
That doesn't really make sense in most cases. If there is a blocked curation, ask the blocking user to test it again. Or delete the RC if they are gone forever.
