### ISSUE TITLE
[Bug] Top Bar of the Help page shows incorrect buttons when logged in

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#5]
When you're logged in and go to the Help page, the top bar shows the buttons that should be there when you're not logged in. The Log Out button is replaced by the Log In button (and clicking it will lead you to the normal login process), and the My Submissions, Profile, Submit, and Browse Submissions buttons are missing.

**Comment by Dri0m** [comment]
fixed in https://github.com/Dri0m/flashpoint-submission-system/commit/97157c42d91e96ebd23d6d5d2679b7b7d14b2fa0
