### ISSUE TITLE
Assign Testing possible despite the submission being rejected

### ISSUE THREAD

**Issue by Curs3dL1ght** [Dri0m/flashpoint-submission-system#59]
As the title say, it's possible to assign testing after a submission has been rejected. If you make the error, you can't un-assign. Actually, you can even assign multiple times.

**Comment by Curs3dL1ght** [comment]
Here an example : [https://fpfss.unstable.life/web/submission/2134](url)

**Comment by Dri0m** [comment]
most likely fixed
