### ISSUE TITLE
[Bug] Browse Submission Versions button on individual curation page has incorrect link

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#6]
The Browse hyperlink in the table links to the correct place, but the blue button on the individual submission pages is incorrect and leads to a 404.

For example, for submission https://fpfss.unstable.life/web/submission/388 which has multiple versions: The hyperlink leads to https://fpfss.unstable.life/web/submission/388/files and the button leads to https://fpfss.unstable.life/submission/388/files

**Comment by Dri0m** [comment]
fixed in https://github.com/Dri0m/flashpoint-submission-system/commit/6e21f4788f73387783e9469e59b9fafdcdc5d23e
