### ISSUE TITLE
Anonymous submissions

### ISSUE THREAD

**Issue by Seirade** [Dri0m/flashpoint-submission-system#69]
Some curators may feel uncomfortable being associated with their submissions, or change their minds about ones they've submitted before. Users should have the option to keep their privacy. In order for anonymity to be possible, some changes have to be made:

- Bots stop including name of uploader in channel announcements (#fpfss-curation-feed). A simple removal of the "by <name>" part of the message would suffice

**For new submissions:**
- Username/ID isn't recorded, set it to belong to a bot (or just none and consider it "orphaned")
- Don't subscribe uploader to notifications, regardless of user settings (#fpfss-notifications)

**For existing submissions:**
- Button that lets you "orphan" a submission
- Deletes uploader's comments
- Removes uploader from subscribed notifications (#fpfss-notifications)

**For everywhere else**
- Same applies for Flashfreeze and submission updates (don't set "Updated by", or set it to a bot/blank)
- Maybe a user setting that lets you submit anonymously by default?

In the past, when uploads were handled through Discord, curation submissions could've become anonymous, either by the user:
A) Deleting their account
B) Deleting the message from the submission channels (which was not allowed, but there was no stopping it)
C) Submitting a curation to unstable.life without leaving a message

Now with FPFSS, anonymous uploads aren't possible. Users also (currently) don't have the option to register using an email address. While a throwaway Discord account could potentially do the job, Discord usually immediately blocks accounts until verified, especially when using disposable email services, so it can be a bit challenging.

**Comment by Dri0m** [comment]
Use a discord throwaway, making emails is *not* an issue when you have so many big emal providers available. This is way too much work for a very niche use-case. If you intend to stay anonymous just on FPFSS, you don't need to do anything else, the site does not see any of your discord details.
