### ISSUE TITLE
[Suggestion] Set submission page title according to the title of the curation

### ISSUE THREAD

**Issue by n0samu** [Dri0m/flashpoint-submission-system#73]
Right now the title of every page on FPFSS is just "Flashpoint's Fantastic Submission System". If submission page titles included the title of the submitted game/animation, it would allow me to keep track of submissions that I previously visited and find them again easily. For example, I could type the title of the game into my browser's address bar to find the submission.

**Comment by Dri0m** [comment]
done in https://github.com/Dri0m/flashpoint-submission-system/commit/94ca87efc209a7038921388fbb54c13b3c7c24ae
