### ISSUE TITLE
[Suggestion] Add a way to see what the file size will be for batch downloads

### ISSUE THREAD

**Issue by Dukktape** [Dri0m/flashpoint-submission-system#9]
Right now when you batch download curations, unless you manually add them up yourself, you have no way of knowing how big the download will be. Some of us don't have the internet to handle a surprise 10GB Ganon curation, and with the number of Youtube games being added, very large batches are quite possible. Even if the file size is just estimated, it will help prevent very large download surprises.

**Comment by Dri0m** [comment]
done in https://github.com/Dri0m/flashpoint-submission-system/commit/d89adee819aaeeabacf27f93f9b3a3f4d0761331
